### ISSUE TITLE
Add Toast Notifications

### ISSUE THREAD

**Issue by Zingzy** [datavorous/amine#10]
The application should toast notifications for the following cases:

- The file path inserted by the user does not exist or is not an exe
- The user entered URL does not exist or is invalid

I would like to work on this issue, if it is planned to be implemented 😄

**Comment by Zingzy** [comment]
The toast notification can either be an in-app notification or a Windows notification using libraries like `win-toasts`.

**Comment by datavorous** [comment]
@Zingzy Check out #7 , we are going to use plyer. I'll notify you once #7 is merged.

**Comment by Zingzy** [comment]
> @Zingzy Check out #7 , we are going to use plyer. I'll notify you once #7 is merged. 

Ok sure

**Comment by datavorous** [comment]
@Zingzy you may start working on it. ive assigned you

**Comment by Zingzy** [comment]
@datavorous I made a PR for this issue, please check 😄

**Comment by datavorous** [comment]
Merged the PR!
