### ISSUE TITLE
Allow adding .exe file paths 

### ISSUE THREAD

**Issue by datavorous** [datavorous/amine#2]
For now, only URLs are opened, enhancements are needed to allow for opening .exe files as well. 

To implement:
Take input > Validate if URL or File Path > Resolve

**Comment by hardikjumnani** [comment]
Hello, I saw the project Amine and was intrigued by the concept of locking a user for productivity. Since, I have worked on these types of projects and have also built a keylogger, I would like to take up this issue.

**Comment by datavorous** [comment]
@hardikjumnani I've assigned you. All the best :)

**Comment by datavorous** [comment]
@hardikjumnani has fixed the issue.
