### ISSUE TITLE
Implement Data Analytics and Insights 

### ISSUE THREAD

**Issue by datavorous** [datavorous/amine#3]
Implement a data storage mechanism, which will store the total duration of time blocks and the date and time of starting, at the end of all the sessions.

Make a separate page which will show the corresponding data in daily, weekly and monthly format. Using line graphs and heatmaps. 

Add an 'export as csv format' aswell.

**Comment by SpreadSheets600** [comment]
Hello, 
I really liked this project, simple and effective. If you don't mind I would like to contribute to it during hacktoberfest and build the analytics mechanism which will be effective. I have a good experience with python and the web.

**Comment by datavorous** [comment]
@SpreadSheets600 Yes absolutely that would be great! Please share what do you plan to implement? Any inputs apart from my existing plan given above?

**Comment by SpreadSheets600** [comment]
Hey, first thing first I would be working on some error handling using exceptions and implementing SQL databases to store the distraction focus time and more, even though I am not that good with the web I would be making a page showing the statistics using pandas and matplotlib.

**Comment by SpreadSheets600** [comment]
@datavorous Hey I got a few cool ideas and suggestions apart form the data management, would you mind if I do it in one or create separate PR ? I am new to open source, if you guide me a bit that would be helpful. BTW I did sent you a friend request on discord.

![image](https://github.com/user-attachments/assets/a52b2d50-774c-4362-9689-152260a92583)
Here this is a simple notification system that could be implemented :)

**Comment by SpreadSheets600** [comment]
@datavorous Hello Again,
Sorry for pinging again, I am bit annoying but this project is honestly amazing. Well here's another suggestion which I am working on and is to track the distractions, like attempting to press buttons and moving mouse to the corners and track them as well.

**Comment by datavorous** [comment]
> @datavorous Hey I got a few cool ideas and suggestions apart form the data management, would you mind if I do it in one or create separate PR ? I am new to open source, if you guide me a bit that would be helpful. BTW I did sent you a friend request on discord.
> 
> ![image](https://private-user-images.githubusercontent.com/115402296/372509479-a52b2d50-774c-4362-9689-152260a92583.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDM2NTUsIm5iZiI6MTcyNzgwMzM1NSwicGF0aCI6Ii8xMTU0MDIyOTYvMzcyNTA5NDc5LWE1MmIyZDUwLTc3NGMtNDM2Mi05Njg5LTE1MjI2MGE5MjU4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxNzIyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Yjk5MzIyNzRiYTkwY2Q3YjIyZDUwY2FiNTczZjdkZGE4YzQyMTY1NzNkODgxZjc2NTI1NzA0NDFlYWM0MDZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Nn43l6nPyz6j8vcxaf-BO6J8r3XGnfuRmlCcSgcXuiI) Here this is a simple notification system that could be implemented :)

Create a separate PR it would be helpful. Im new to OpenSource as well :) 
Are you using win11toast for notifications? I couldn't make it work properly and got timed out errors repeatedly, let me know if it works properly in your implementation after some test runs.

**Comment by datavorous** [comment]
> @datavorous Hello Again, Sorry for pinging again, I am bit annoying but this project is honestly amazing. Well here's another suggestion which I am working on and is to track the distractions, like attempting to press buttons and moving mouse to the corners and track them as well.

That seems cool! I'll get back to you on discord tomorrow. :)

**Comment by SpreadSheets600** [comment]
@datavorous i just finished working on the data visulaization, csv export and distraction tracking. It needs a lot of improvement that i will do ... later tomorrow and for now these are the update .... 

![image](https://github.com/user-attachments/assets/99db878b-ac50-488c-a8e7-08797e4416cf)
![image](https://github.com/user-attachments/assets/d8239b25-e40e-4511-b005-a467e51bd137)
![image](https://github.com/user-attachments/assets/295f8905-5673-4747-bc3c-94bbb088e386)


I am opening a PR in few minutes, sorry it contains the notification stuff using `plyer` module since win11tost doesn't work well in windows 10 :)

**Comment by SpreadSheets600** [comment]
> > @datavorous Hello Again, Sorry for pinging again, I am bit annoying but this project is honestly amazing. Well here's another suggestion which I am working on and is to track the distractions, like attempting to press buttons and moving mouse to the corners and track them as well.
> 
> That seems cool! I'll get back to you on discord tomorrow. :)

Great it would be helpful to communicate
